# Generated by Django 4.0.5 on 2022-06-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqrroot_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='root1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='number',
            name='root2',
            field=models.IntegerField(blank=True),
        ),
    ]
