# Generated by Django 4.0.5 on 2022-06-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqrroot_calc', '0002_alter_number_root1_alter_number_root2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='root1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='number',
            name='root2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
