# Generated by Django 4.0.5 on 2022-06-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqrroot_calc', '0004_remove_number_root1_remove_number_root2'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='root1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='number',
            name='root2',
            field=models.FloatField(default=12345),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='number',
            name='a',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='number',
            name='b',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='number',
            name='c',
            field=models.FloatField(),
        ),
    ]
