# Generated by Django 4.0.5 on 2022-06-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqrroot_calc', '0005_number_root1_number_root2_alter_number_a_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Number',
            new_name='SquareRoots',
        ),
    ]
