# Generated by Django 4.0.5 on 2022-06-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqrroot_calc', '0009_alter_squareroots_root1_alter_squareroots_root2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squareroots',
            name='root1',
            field=models.FloatField(blank=True, default=12345),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squareroots',
            name='root2',
            field=models.FloatField(blank=True, default=12345),
            preserve_default=False,
        ),
    ]
